In [46]:
import json
import re
import unidecode

import pandas as pd
import numpy as np

from futbolean.io import JSONRemoteDataSet
from futbolean.data_import import epl_player_data
from futbolean import run

In [4]:
player_data = context.run(pipeline_name='epl_player')
player_df = pd.DataFrame(player_data.get('clean_epl_players'))
player_df

2019-11-05 23:28:27,740 - root - INFO - ** Kedro project app
2019-11-05 23:28:27,880 - kedro.versioning.journal - WARNING - Unable to git describe /app
2019-11-05 23:28:27,892 - kedro.journal - INFO - {"type": "ContextJournalRecord", "run_id": "2019-11-05T23.28.27.763Z", "project_path": "/app", "env": "local", "kedro_version": "0.15.4", "tags": null, "from_nodes": null, "to_nodes": null, "node_names": null, "from_inputs": null, "load_versions": null, "pipeline_name": "epl_player", "git_sha": null}
2019-11-05 23:28:28,050 - kedro.io.data_catalog - INFO - Loading data from `epl_player_matches` (JSONLocalDataSet)...
2019-11-05 23:28:35,367 - kedro.pipeline.node - INFO - Running node: clean([epl_player_matches]) -> [clean_epl_players]
2019-11-05 23:28:40,595 - kedro.io.data_catalog - INFO - Saving data to `clean_epl_players` (MemoryDataSet)...
2019-11-05 23:28:40,835 - kedro.runner.sequential_runner - INFO - Completed 1 out of 1 tasks
2019-11-05 23:28:40,854 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
2019-11-05 23:28:40,861 - kedro.io.data_catalog - INFO - Loading data from `clean_epl_players` (MemoryDataSet)...

,,day,comp,round,venue,result,squad,opponent,start,min,offense_gls,...,national_team,goalkeeping_cs,goalkeeping_ga,goalkeeping_saves,goalkeeping_so_ta,goalkeeping_save_percentage,expectedx_g,expectedx_g-pk,expectedx_a,player_name
date,player,,,,,,,,,,,,,,,,,,,,,
2014-08-16,Mohamed Diame,Sat,Premier League,Matchweek 1,Home,L 0–1,West Ham,Tottenham,N,22,0,...,,0,0,0,0,0.0,NaN,NaN,NaN,Mohamed Diamé
2014-08-23,Mohamed Diame,Sat,Premier League,Matchweek 2,Away,W 3–1,West Ham,Crystal Palace,N,0,0,...,,0,0,0,0,0.0,NaN,NaN,NaN,Mohamed Diamé
2014-08-26,Mohamed Diame,Tue,League Cup,Second Round,Home,L 1 (4)–1 (5),West Ham,Sheffield Utd,Y,120,0,...,,0,0,0,0,0.0,NaN,NaN,NaN,Mohamed Diamé
2014-08-30,Mohamed Diame,Sat,Premier League,Matchweek 3,Home,L 1–3,West Ham,Southampton,N,32,0,...,,0,0,0,0,0.0,NaN,NaN,NaN,Mohamed Diamé
2014-09-15,Mohamed Diame,Mon,Premier League,Matchweek 4,Home,D 2–2,Hull City,West Ham,Y,79,1,...,,0,0,0,0,0.0,NaN,NaN,NaN,Mohamed Diamé
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-19,Ollie Shenton,Fri,PL2 — Div. 2,Matchweek 16,Away,D 2–2,Stoke City,Middlesbrough,Y,90,0,...,,0,0,0,0,0.0,NaN,NaN,NaN,Ollie Shenton
2019-04-26,Ollie Shenton,Fri,PL2 — Div. 2,Matchweek 22,Home,W 2–1,Stoke City,Reading,Y,90,0,...,,0,0,0,0,0.0,NaN,NaN,NaN,Ollie Shenton
2019-08-12,Ollie Shenton,Mon,PL2 — Div. 2,Matchweek 1,Home,D 1–1,Stoke City,Sunderland,Y,90,0,...,,0,0,0,0,0.0,NaN,NaN,NaN,Ollie Shenton
2019-08-16,Ollie Shenton,Fri,PL2 — Div. 2,Matchweek 2,Away,W 2–0,Stoke City,Middlesbrough,Y,90,1,...,,0,0,0,0,0.0,NaN,NaN,NaN,Ollie Shenton
2019-08-26,Ollie Shenton,Mon,PL2 — Div. 2,Matchweek 3,Home,L 0–1,Stoke City,Fulham,Y,85,0,...,,0,0,0,0,0.0,NaN,NaN,NaN,Ollie Shenton

In [20]:
player_df['position'].drop_duplicates(keep='last')

date        player
2019-10-05  Christian Eriksen             DF-MF (AM)
            Alex Iwobi                       FW (WM)
2019-10-02  Alex Oxlade-Chamberlain       MF (CM-WM)
2019-10-05  Stefan Johansen               MF (AM-CM)
            Vicente Iborra                MF (AM-DM)
            Cesc Fabregas              FW-MF (AM-CM)
            Sam Surridge
2019-09-13  Markus Suttner                     DF-GK
2018-11-08  Yaya Toure                    MF (CD-CM)
2019-10-05  Francis Coquelin           DF-MF (DM-FB)
2019-03-09  Vurnon Anita                  DF-MF (FB)
2019-09-22  Baba Rahman                   DF (CD-FB)
2019-05-12  Juan Carlos Paredes        DF-MF (FB-WM)
2019-10-06  Gokhan Inler                  MF (CM-DM)
2017-01-04  Esteban Cambiasso                MF (DM)
2016-11-12  Paul Konchesky                     DF-FW
2019-10-07  Liam Bridcutt                 DF-MF (DM)
2017-12-02  Chris Baird                   DF-MF (CD)
2019-10-05  Benjamin Stambouli         DF-MF (CD-DM)
2019-08-31  Ross Wallace                  FW-MF (WM)
2018-01-20  Dwight Tiendalli                 DF (FB)
2015-02-07  Valentin Roberge                 DF (CD)
2019-08-25  Fredrik Ulvestad                   DF-MF
2019-08-14  Nani                       FW-MF (AM-WM)
2019-08-18  Sebastian Blanco              FW-MF (AM)
2019-10-05  Lewis Holtby                  MF (AM-WM)
2018-01-12  Jussi Jaaskelainen                    GK
2017-01-28  Lloyd Isgrove                    MF (WM)
2019-10-05  Haris Vuckic                     MF (AM)
2017-01-02  Jerome Thomas                      FW-MF
2019-10-05  Dominic Gape                     MF (CM)
2017-05-05  Ryan Seager                           FW
2018-02-08  Tom Thorpe                            DF
2019-08-26  Ollie Shenton                         MF
Name: position, dtype: object

In [42]:
(
    player_df
    .query('comp == "Premier League" & position == "DF-FW"')
    .sort_index()
    .loc[(slice('2019-01-01', None), slice(None)), ['player_name', 'squad', 'position']]
    .drop_duplicates('player_name')
    .sort_values('squad')
)

                                player_name           squad position
date       player
2019-01-29 Stephen Ward        Stephen Ward         Burnley    DF-FW
2019-01-01 Callum Paterson  Callum Paterson    Cardiff City    DF-FW
2019-01-02 Jeffrey Schlupp  Jeffrey Schlupp  Crystal Palace    DF-FW
2019-01-01 Jonjoe Kenny        Jonjoe Kenny         Everton    DF-FW
2019-01-02 Erik Durm              Erik Durm    Huddersfield    DF-FW
2019-01-01 Ricardo Pereira  Ricardo Pereira  Leicester City    DF-FW
2019-08-11 Ashley Young        Ashley Young  Manchester Utd    DF-FW

In [16]:
player_df.columns

Index(['day', 'comp', 'round', 'venue', 'result', 'squad', 'opponent', 'start',
       'min', 'offense_gls', 'offense_ast', 'offense_sh', 'offense_so_t',
       'offense_crs', 'offense_fld', 'offense_pk', 'offense_p_katt',
       'defense_tkl', 'defense_int', 'defense_fls', 'defense_crd_y',
       'defense_crd_r', 'position', 'height_cm', 'weight_kg', 'birthdate',
       'national_team', 'goalkeeping_cs', 'goalkeeping_ga',
       'goalkeeping_saves', 'goalkeeping_so_ta', 'goalkeeping_save_percentage',
       'expectedx_g', 'expectedx_g-pk', 'expectedx_a', 'player_name'],
      dtype='object')

In [43]:
player_df['offense_ast']

date        player
2014-08-16  Mohamed Diame    0
2014-08-23  Mohamed Diame    0
2014-08-26  Mohamed Diame    0
2014-08-30  Mohamed Diame    0
2014-09-15  Mohamed Diame    0
                            ..
2019-04-19  Ollie Shenton    0
2019-04-26  Ollie Shenton    0
2019-08-12  Ollie Shenton    0
2019-08-16  Ollie Shenton    0
2019-08-26  Ollie Shenton    0
Name: offense_ast, Length: 117740, dtype: int64

In [45]:
player_df.query('offense_p_katt > 0')[['offense_pk', 'offense_p_katt']]

                            offense_pk  offense_p_katt
date       player
2016-12-03 Steven Fletcher           1               1
2016-12-17 Steven Fletcher           1               1
2019-08-31 Steven Fletcher           1               1
2018-04-28 Rhys Healey               1               1
2016-10-01 Tom Cairney               0               1
...                                ...             ...
2017-08-09 Mikael Mandron            0               1
2017-11-25 Mikael Mandron            0               1
2017-01-06 Ryan Seager               1               1
2017-01-30 Ryan Seager               0               1
2017-03-13 Ryan Seager               1               1

[1284 rows x 2 columns]

In [49]:
np.array([1.2, 3.9]).astype(int)

array([1, 3])

In [53]:
player_df.eval("offense_p_katt - offense_pk - 5")

date        player
2014-08-16  Mohamed Diame   -5
2014-08-23  Mohamed Diame   -5
2014-08-26  Mohamed Diame   -5
2014-08-30  Mohamed Diame   -5
2014-09-15  Mohamed Diame   -5
                            ..
2019-04-19  Ollie Shenton   -5
2019-04-26  Ollie Shenton   -5
2019-08-12  Ollie Shenton   -5
2019-08-16  Ollie Shenton   -5
2019-08-26  Ollie Shenton   -5
Length: 117740, dtype: int64